inherit_from: .rubocop_todo.yml

Layout/LineLength:
  Exclude:
    - 'bin/*'

Style/Documentation:
  Enabled: false

Metrics/PerceivedComplexity:
  Exclude:
    - 'bin/*'

Metrics/MethodLength:
  Exclude:
    - 'bin/*'